#!/usr/bin/env python3
"""
Prepare training data with FIXED train/val/test splits.

This script:
1. Loads vocabularies.json (generated by generate_vocabularies.py)
2. Loads labeled_data.csv (with pre-assigned f_num from disambiguation)
3. Assigns a deterministic split (train/val/test) based on query hash
4. Saves to training_examples.json with splits marked

All downstream scripts (mine_negatives.py, train_*.py) should use
the pre-assigned splits rather than re-splitting.
"""

import csv
import hashlib
import json
import re
from collections import defaultdict
from pathlib import Path

DATA_DIR = Path(__file__).parent / "data"
VOCAB_PATH = DATA_DIR / "vocabularies.json"
FNUM_RECORDS_PATH = DATA_DIR / "fnum_to_records.json"
OUTPUT_PATH = DATA_DIR / "training_examples.json"


# Map from query text keywords to desig_name abbreviations.
# Ordered longest-first so "local lodge" matches before "local".
DESIG_KEYWORDS = [
    ("local joint executive board", {"LJEB"}),
    ("joint executive board", {"JEB"}),
    ("building trades council", {"BCTC"}),
    ("local joint board", {"LJB"}),
    ("state association", {"SA", "ASSN"}),
    ("district council", {"DC"}),
    ("district lodge", {"DLG"}),
    ("local division", {"LDIV"}),
    ("local chapter", {"LCH"}),
    ("local lodge", {"LLG"}),
    ("local union", {"LU"}),
    ("joint board", {"JB"}),
    ("joint council", {"JC"}),
    ("state council", {"STC"}),
    ("sub-federation", {"SFED"}),
    ("national headquarters", {"NHQ"}),
    ("headquarters", {"NHQ"}),
    ("association", {"ASSN", "SA"}),
    ("conference", {"CONF"}),
    ("federation", {"SFED"}),
    ("division", {"DIV", "LDIV"}),
    ("district", {"D", "DC"}),
    ("council", {"C", "LEADC", "DC", "JC", "STC", "BCTC"}),
    ("chapter", {"CH", "LCH"}),
    ("branch", {"BR"}),
    ("lodge", {"LG", "LLG", "DLG"}),
    ("local", {"LU", "LOCAL"}),
    ("unit", {"UNIT"}),
]


# When multiple desig_names remain after keyword matching, prefer the
# first over the alternates.  E.g. keep "C" over "LEADC", "LU" over "LOCAL".
DESIG_PREFERENCE = [
    ("C", {"LEADC"}),
    ("LU", {"LOCAL", "LG", "LLG", "NHQ", "DALU"}),
    ("LLG", {"LG"}),
    ("DC", {"DIV"}),
    ("D", {"DC"}),
    ("SA", {"ASSN"}),
    ("STC", {"DLG"}),
]


def filter_records_by_query(query: str, records: list) -> list:
    """
    Filter record variants to those matching the query.

    Three stages:
    1. desig_num: if records have different desig_nums, keep only those
       whose desig_num appears in the query (2-6 digit numbers).
    2. prefix/suffix: positive match first (query specifies prefix/suffix),
       then inverse filter (keep plain variants when query doesn't specify).
    3. desig_name: positive keyword match first (query contains "district",
       "lodge", etc.), then inverse filter (keep non-blank when mixed).
    """
    if len(records) <= 1:
        return records

    # Extract numbers from query
    all_query_nums = set(int(n) for n in re.findall(r"\d+", query))

    # Stage 1: filter by desig_num
    query_nums_pos = set(n for n in all_query_nums if n >= 1)
    record_nums = set(r["desig_num"] for r in records)
    if len(record_nums) > 1:
        # Positive match: keep records whose desig_num appears in query
        if query_nums_pos:
            matching = [r for r in records if r["desig_num"] in query_nums_pos]
            if matching:
                records = matching
        # Inverse filter: if query has no numbers, keep desig_num=0 records
        record_nums = set(r["desig_num"] for r in records)
        if len(record_nums) > 1 and 0 in record_nums and not query_nums_pos:
            zero_recs = [r for r in records if r["desig_num"] == 0]
            if zero_recs:
                records = zero_recs

    # Stage 2: filter by prefix and suffix
    # First try positive matches (query specifies prefix or suffix),
    # then fall back to inverse matches (keep plain variants).
    # Positive matches run first so they aren't preempted by inverse filters.
    # Suffixes can appear after numbers (1036-C, 748L) or before (D583, W-261)
    # Codes adjacent to numbers may also be desig_name abbreviations (D, LG, DC)
    after_num = re.findall(r"\d-?([A-Za-z]{1,3})\b", query)
    # Single-letter suffixes can also be separated by a space (985 L, 160 C).
    # Limit to single letters to avoid capturing geographic codes (5 PA, 1 NY).
    after_num += re.findall(r"\d\s([A-Za-z])\b", query)
    before_num = re.findall(r"(?<!\w)([A-Za-z]{1,3})-?\d", query)
    query_codes = set(m.upper() for m in after_num + before_num)
    # Also extract numeric suffixes: short numbers after a hyphen following a longer
    # number, e.g. "1410-1" -> "1", "662-04" -> "4".  Only match 1-2 digit suffixes
    # after a 3+ digit number to avoid confusing with prefix-number patterns.
    numeric_suf = re.findall(r"\d{3,}-0*(\d{1,2})\b", query)
    query_suffixes = query_codes | set(numeric_suf)

    # Try positive prefix match
    record_prefixes = set(r.get("prefix", 0) for r in records)
    prefix_matched = False
    if len(record_prefixes) > 1 and all_query_nums:
        prefix_matching = [
            r
            for r in records
            if r.get("prefix", 0) != 0 and r.get("prefix", 0) in all_query_nums
        ]
        if prefix_matching:
            records = prefix_matching
            prefix_matched = True

    # Try positive suffix match
    record_suffixes = set(r.get("suffix", "") for r in records)
    suffix_matched = False

    def _norm_suffix(s):
        """Normalize suffix for comparison: strip leading zeros from numeric."""
        s = s.strip().upper()
        if s.isdigit():
            return str(int(s))
        return s

    query_suffixes_norm = set(_norm_suffix(s) for s in query_suffixes)
    if len(record_suffixes) > 1 and query_suffixes_norm:
        suffix_matching = [
            r
            for r in records
            if r.get("suffix", "") and _norm_suffix(r["suffix"]) in query_suffixes_norm
        ]
        if suffix_matching:
            records = suffix_matching
            suffix_matched = True

    # Inverse filters: if query doesn't specify prefix/suffix, keep plain variants
    if not prefix_matched:
        record_prefixes = set(r.get("prefix", 0) for r in records)
        if len(record_prefixes) > 1:
            no_prefix = [r for r in records if r.get("prefix", 0) == 0]
            if no_prefix:
                records = no_prefix

    if not suffix_matched:
        record_suffixes = set(r.get("suffix", "") for r in records)
        if len(record_suffixes) > 1:
            no_suffix = [r for r in records if not r.get("suffix", "")]
            if no_suffix:
                records = no_suffix

    # Stage 3: filter by desig_name
    desig_names = set(r.get("desig_name", "") for r in records)
    if len(desig_names) > 1:
        # Positive match: check if query contains a designation keyword
        query_lower = query.lower()
        desig_matched = False
        for keyword, desig_set in DESIG_KEYWORDS:
            if keyword in query_lower:
                matching = [r for r in records if r.get("desig_name", "") in desig_set]
                if matching:
                    records = matching
                    desig_matched = True
                break  # stop at first keyword match (longest first)

        # Try matching codes extracted near numbers against desig_name
        if not desig_matched and query_codes:
            desig_names = set(r.get("desig_name", "") for r in records)
            code_matching = [
                r for r in records if r.get("desig_name", "") in query_codes
            ]
            if code_matching:
                records = code_matching
                desig_matched = True

        # Inverse filter: if no keyword match, keep non-blank desig_name
        if not desig_matched:
            desig_names = set(r.get("desig_name", "") for r in records)
            if len(desig_names) > 1 and "" in desig_names:
                non_blank = [r for r in records if r.get("desig_name", "")]
                if non_blank:
                    records = non_blank

        # Preference filter: when keyword matched multiple synonyms,
        # pick the more common/generic variant.
        desig_names = set(r.get("desig_name", "") for r in records)
        if len(desig_names) > 1:
            for preferred, alternates in DESIG_PREFERENCE:
                if preferred in desig_names and desig_names & alternates:
                    keep = [
                        r for r in records if r.get("desig_name", "") not in alternates
                    ]
                    if keep:
                        records = keep
                    break

    return records


def record_signature(record):
    """Return a hashable tuple of all record fields (including unit_id)."""
    return (
        record.get("union_name", ""),
        record.get("desig_name", ""),
        record.get("desig_num", 0),
        record.get("prefix", 0),
        record.get("suffix", ""),
        record.get("unit_id", ""),
    )


def build_record_index(fnum_to_records):
    """
    Build a reverse index: record_signature -> set of f_nums that have it.

    Used to quickly find competing f_nums for the ambiguity check.
    """
    sig_to_fnums = defaultdict(set)
    for fnum, records in fnum_to_records.items():
        for rec in records:
            sig_to_fnums[record_signature(rec)].add(fnum)
    return sig_to_fnums


def is_ambiguous(query, f_num, fnum_to_records, sig_to_fnums):
    """
    Check if a training example is ambiguous.

    A training example is ambiguous if another f_num produces an identical
    filtered record (including unit_id) for this query. This means:
    - F_nums in conflict groups have different unit_ids, so they won't match
      even if other fields are identical -> not ambiguous (model can learn unit_id).
    - F_nums NOT in conflict groups share unit_id="" -> if other fields also
      match, they're truly ambiguous -> filter out.
    """
    filtered = filter_records_by_query(query, fnum_to_records[f_num])
    if not filtered:
        return True

    target_sig = record_signature(filtered[0])

    # Find f_nums that have any record matching this signature
    candidates = sig_to_fnums.get(target_sig, set())
    competing = candidates - {f_num}
    if not competing:
        return False

    # Verify: does filter_records_by_query for the competing f_num
    # actually produce this same record for this query?
    for other_fnum in competing:
        other_filtered = filter_records_by_query(query, fnum_to_records[other_fnum])
        if other_filtered and record_signature(other_filtered[0]) == target_sig:
            return True

    return False


def get_split(query: str, val_frac: float = 0.1, test_frac: float = 0.1) -> str:
    """
    Deterministically assign a split based on query hash.

    This ensures the same query always gets the same split,
    regardless of when or how many times the script is run.
    """
    h = hashlib.md5(query.encode()).hexdigest()
    val = int(h[:8], 16) / (16**8)

    if val < val_frac:
        return "val"
    elif val < val_frac + test_frac:
        return "test"
    else:
        return "train"


def load_vocabularies():
    """Load vocabularies from vocabularies.json."""
    print(f"Loading vocabularies from {VOCAB_PATH}...")
    with open(VOCAB_PATH) as f:
        vocab = json.load(f)

    fnum_to_idx = {int(k): v for k, v in vocab["fnum_to_idx"].items()}
    fnum_set = set(fnum_to_idx.keys())

    print(f"  {len(fnum_set)} f_nums in vocabulary")

    return fnum_set


def load_fnum_records():
    """Load fnum_to_records from fnum_to_records.json."""
    print(f"Loading fnum_to_records from {FNUM_RECORDS_PATH}...")
    with open(FNUM_RECORDS_PATH) as f:
        data = json.load(f)

    fnum_to_records = {int(k): v for k, v in data.items()}
    total_variants = sum(len(v) for v in fnum_to_records.values())
    print(f"  {len(fnum_to_records)} f_nums with {total_variants} record variants")

    return fnum_to_records


def load_labeled_data(fnum_set, fnum_to_records, sig_to_fnums):
    """Load labeled_data.csv using pre-assigned f_num values."""
    examples = []
    skipped_no_fnum = 0
    skipped_not_in_vocab = 0
    skipped_ambiguous = 0

    with open(DATA_DIR / "labeled_data.csv") as f:
        reader = csv.DictReader(f)
        for row in reader:
            text = row["text"]
            aff = row["aff_abbr"]

            # Use pre-assigned f_num
            fnum_str = row.get("f_num", "").strip()
            if not fnum_str:
                skipped_no_fnum += 1
                continue

            try:
                f_num = int(float(fnum_str))
            except ValueError:
                skipped_no_fnum += 1
                continue

            # Validate f_num is in vocabulary and has records
            if f_num not in fnum_set or f_num not in fnum_to_records:
                skipped_not_in_vocab += 1
                continue

            # Filter out ambiguous examples where another f_num produces
            # an identical record (including unit_id) for this query
            if is_ambiguous(text, f_num, fnum_to_records, sig_to_fnums):
                skipped_ambiguous += 1
                continue

            # Filter records to match numbers in query
            records = filter_records_by_query(text, fnum_to_records[f_num])

            examples.append(
                {
                    "query": text,
                    "f_num": f_num,
                    "source": "labeled",
                    "aff_abbr": aff,
                    "records": records,
                }
            )

    print(f"  {len(examples)} examples loaded")
    print(
        f"  Skipped: {skipped_no_fnum} no f_num, {skipped_not_in_vocab} not in vocab,"
        f" {skipped_ambiguous} ambiguous"
    )

    return examples


def load_synthetic_data(fnum_set, fnum_to_records, sig_to_fnums):
    """Load unaff_synthetic.csv using pre-assigned f_num values."""
    examples = []

    unaff_path = DATA_DIR / "unaff_synthetic.csv"
    if not unaff_path.exists():
        print("  No unaff_synthetic.csv found, skipping")
        return examples

    skipped_no_fnum = 0
    skipped_not_in_vocab = 0
    skipped_ambiguous = 0

    with open(unaff_path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            text = row["text"]

            fnum_str = row.get("f_num", "").strip()
            if not fnum_str:
                skipped_no_fnum += 1
                continue

            try:
                f_num = int(float(fnum_str))
            except ValueError:
                skipped_no_fnum += 1
                continue

            if f_num not in fnum_set or f_num not in fnum_to_records:
                skipped_not_in_vocab += 1
                continue

            if is_ambiguous(text, f_num, fnum_to_records, sig_to_fnums):
                skipped_ambiguous += 1
                continue

            # Filter records to match numbers in query
            records = filter_records_by_query(text, fnum_to_records[f_num])

            examples.append(
                {
                    "query": text,
                    "f_num": f_num,
                    "source": "synthetic",
                    "aff_abbr": "UNAFF",
                    "records": records,
                }
            )

    print(f"  {len(examples)} examples loaded")
    if skipped_no_fnum or skipped_not_in_vocab or skipped_ambiguous:
        print(
            f"  Skipped: {skipped_no_fnum} no f_num, {skipped_not_in_vocab} not in vocab,"
            f" {skipped_ambiguous} ambiguous"
        )

    return examples


UNIT_ID_CSV = Path(__file__).parent / "fnum_to_unit_identifier.csv"


def load_conflict_groups():
    """Load conflict group (component_id) for each f_num."""
    fnum_to_component = {}
    with open(UNIT_ID_CSV) as f:
        for row in csv.DictReader(f):
            fnum_to_component[int(row["f_num"])] = int(row["component_id"])
    return fnum_to_component


def add_structural_negatives(examples, fnum_to_records):
    """
    Add structural hard negatives: records with the same union+number
    but a different f_num.

    These surface suffix, desig_name, and prefix disambiguation cases
    that ANCE mining misses because they have nearly identical embeddings.

    Skips candidates that:
    - Match any positive record variant on (desig_name, prefix, suffix)
    - Are in the same conflict group as the positive (those need unit_id
      to disambiguate, which is handled separately)
    """
    fnum_to_component = load_conflict_groups()

    # Build index: (union_name, desig_num) -> [(fnum, record), ...]
    union_num_index = defaultdict(list)
    for fnum, records in fnum_to_records.items():
        for rec in records:
            if rec["desig_num"] > 0:
                key = (rec["union_name"], rec["desig_num"])
                union_num_index[key].append((fnum, rec))

    total_added = 0
    examples_with_structural = 0

    for ex in examples:
        pos_fnum = ex["f_num"]
        pos_records = ex["records"]
        if not pos_records:
            continue

        pos_rec = pos_records[0]
        if pos_rec["desig_num"] == 0:
            continue

        key = (pos_rec["union_name"], pos_rec["desig_num"])
        group = union_num_index.get(key, [])

        # Build the set of all record shapes for the positive f_num
        # (ignoring unit_id) so we never add a negative that matches
        # any positive variant
        pos_shapes = set()
        for rec in fnum_to_records[pos_fnum]:
            pos_shapes.add(
                (
                    rec.get("desig_name", ""),
                    rec.get("prefix", 0),
                    rec.get("suffix", ""),
                )
            )

        # Collect structural negatives from different fnums
        pos_component = fnum_to_component.get(pos_fnum)
        structural = []
        for cand_fnum, cand_rec in group:
            if cand_fnum == pos_fnum:
                continue

            # Skip if in the same conflict group — those pairs share
            # a representation and need unit_id to disambiguate
            if (
                pos_component is not None
                and fnum_to_component.get(cand_fnum) == pos_component
            ):
                continue

            # Skip if this record's shape matches any positive variant
            cand_shape = (
                cand_rec.get("desig_name", ""),
                cand_rec.get("prefix", 0),
                cand_rec.get("suffix", ""),
            )
            if cand_shape in pos_shapes:
                continue

            structural.append({"f_num": cand_fnum, "record": cand_rec})

        if structural:
            # Deduplicate by record shape — we only need one representative
            # per distinct (desig_name, prefix, suffix) combination
            seen = set()
            deduped = []
            for s in structural:
                r = s["record"]
                shape = (
                    r.get("desig_name", ""),
                    r.get("prefix", 0),
                    r.get("suffix", ""),
                )
                if shape not in seen:
                    seen.add(shape)
                    deduped.append(s)
            ex["structural_negatives"] = deduped
            total_added += len(deduped)
            examples_with_structural += 1

    print(
        f"  {total_added} structural negatives added"
        f" to {examples_with_structural} examples"
    )


def classify_fnum_discrimination(fnum_to_records):
    """
    For each f_num, determine if (union_name, desig_num) uniquely identifies it.

    Returns dict: fnum -> category string:
      "unique"    — unique by (union_name, desig_num), or no desig_num
      "ambiguous" — shares (union_name, desig_num) with other f_nums
    """
    # Build (union_name, desig_num) -> set of f_nums
    union_num_to_fnums = defaultdict(set)
    for fnum, records in fnum_to_records.items():
        for rec in records:
            if rec["desig_num"] > 0:
                key = (rec["union_name"], rec["desig_num"])
                union_num_to_fnums[key].add(fnum)

    ambiguous_fnums = set()
    for fnums in union_num_to_fnums.values():
        if len(fnums) > 1:
            ambiguous_fnums.update(fnums)

    return {
        fnum: "ambiguous" if fnum in ambiguous_fnums else "unique"
        for fnum in fnum_to_records
    }


def add_example_categories(examples, fnum_to_records):
    """
    Add a discrimination category to each example based on whether
    (union_name, desig_num) uniquely identifies its f_num.

    Categories: unique, ambiguous
    """
    fnum_category = classify_fnum_discrimination(fnum_to_records)

    # Assign category to each example
    train_counts = defaultdict(int)
    total_train = 0
    for ex in examples:
        cat = fnum_category.get(ex["f_num"], "unique")
        ex["category"] = cat
        if ex.get("split") == "train":
            train_counts[cat] += 1
            total_train += 1

    # Print distribution
    print("  Training distribution:")
    for cat in sorted(train_counts, key=lambda c: train_counts[c], reverse=True):
        print(
            f"    {cat:>8s}: {train_counts[cat]:>6d} ({100*train_counts[cat]/total_train:.1f}%)"
        )


def main():
    # Load vocabularies
    fnum_set = load_vocabularies()

    # Load fnum_to_records
    fnum_to_records = load_fnum_records()

    # Build record index for ambiguity checking
    print("\nBuilding record index...")
    sig_to_fnums = build_record_index(fnum_to_records)

    # Load labeled data
    print("\nLoading labeled data...")
    labeled = load_labeled_data(fnum_set, fnum_to_records, sig_to_fnums)

    # Load synthetic data
    print("\nLoading synthetic data...")
    synthetic = load_synthetic_data(fnum_set, fnum_to_records, sig_to_fnums)

    # Assign splits: labeled data gets train/val/test, synthetic is train only
    print("\nAssigning splits...")
    split_counts = defaultdict(int)

    for ex in labeled:
        ex["split"] = get_split(ex["query"])
        split_counts[ex["split"]] += 1

    for ex in synthetic:
        ex["split"] = "train"
        split_counts["train"] += 1

    # Combine
    examples = labeled + synthetic
    print(f"\nTotal: {len(examples)} examples")
    print(f"  Train: {split_counts['train']} (labeled + synthetic)")
    print(f"  Val: {split_counts['val']} (labeled only)")
    print(f"  Test: {split_counts['test']} (labeled only)")

    # Add structural negatives
    print("\nAdding structural negatives...")
    add_structural_negatives(examples, fnum_to_records)

    # Assign discrimination categories to examples
    print("\nAssigning discrimination categories...")
    add_example_categories(examples, fnum_to_records)

    # Save
    print(f"\nSaving to {OUTPUT_PATH}...")
    with open(OUTPUT_PATH, "w") as f:
        json.dump(examples, f, indent=2)

    print("Done!")


if __name__ == "__main__":
    main()
