#!/usr/bin/env python3
"""
Prepare training data with FIXED train/val/test splits.

This script:
1. Loads vocabularies.json (generated by generate_vocabularies.py)
2. Loads labeled_data.csv (with pre-assigned f_num from disambiguation)
3. Assigns a deterministic split (train/val/test) based on query hash
4. Saves to training_examples.json with splits marked

All downstream scripts (mine_negatives.py, train_*.py) should use
the pre-assigned splits rather than re-splitting.
"""

import csv
import hashlib
import json
import re
from collections import defaultdict
from pathlib import Path

DATA_DIR = Path(__file__).parent / "data"
VOCAB_PATH = DATA_DIR / "vocabularies.json"
FNUM_RECORDS_PATH = DATA_DIR / "fnum_to_records.json"
OUTPUT_PATH = DATA_DIR / "training_examples.json"


def filter_records_by_query(query: str, records: list) -> list:
    """
    Filter record variants to those whose desig_num matches numbers in the query.

    This handles cases like IUE-CWA where the same f_num has both
    short (134) and long (81134) number variants. We want to train on
    the variant that matches what's in the query text.
    """
    if len(records) <= 1:
        return records

    # Extract numbers from query (2-6 digits)
    query_nums = set(int(n) for n in re.findall(r"\b\d{2,6}\b", query))
    if not query_nums:
        return records

    # Check if records have different desig_nums
    record_nums = set(r["desig_num"] for r in records)
    if len(record_nums) <= 1:
        return records

    # Filter to records where desig_num is in query
    matching = [r for r in records if r["desig_num"] in query_nums]

    # Return matching if any, otherwise all records
    return matching if matching else records


def get_split(query: str, val_frac: float = 0.1, test_frac: float = 0.1) -> str:
    """
    Deterministically assign a split based on query hash.

    This ensures the same query always gets the same split,
    regardless of when or how many times the script is run.
    """
    h = hashlib.md5(query.encode()).hexdigest()
    val = int(h[:8], 16) / (16**8)

    if val < val_frac:
        return "val"
    elif val < val_frac + test_frac:
        return "test"
    else:
        return "train"


def load_vocabularies():
    """Load vocabularies from vocabularies.json."""
    print(f"Loading vocabularies from {VOCAB_PATH}...")
    with open(VOCAB_PATH) as f:
        vocab = json.load(f)

    fnum_to_idx = {int(k): v for k, v in vocab["fnum_to_idx"].items()}
    fnum_set = set(fnum_to_idx.keys())

    print(f"  {len(fnum_set)} f_nums in vocabulary")

    return fnum_set


def load_fnum_records():
    """Load fnum_to_records from fnum_to_records.json."""
    print(f"Loading fnum_to_records from {FNUM_RECORDS_PATH}...")
    with open(FNUM_RECORDS_PATH) as f:
        data = json.load(f)

    fnum_to_records = {int(k): v for k, v in data.items()}
    total_variants = sum(len(v) for v in fnum_to_records.values())
    print(f"  {len(fnum_to_records)} f_nums with {total_variants} record variants")

    return fnum_to_records


def load_labeled_data(fnum_set, fnum_to_records):
    """Load labeled_data.csv using pre-assigned f_num values."""
    examples = []
    skipped_no_fnum = 0
    skipped_not_in_vocab = 0

    with open(DATA_DIR / "labeled_data.csv") as f:
        reader = csv.DictReader(f)
        for row in reader:
            text = row["text"]
            aff = row["aff_abbr"]

            # Use pre-assigned f_num
            fnum_str = row.get("f_num", "").strip()
            if not fnum_str:
                skipped_no_fnum += 1
                continue

            try:
                f_num = int(float(fnum_str))
            except ValueError:
                skipped_no_fnum += 1
                continue

            # Validate f_num is in vocabulary and has records
            if f_num not in fnum_set or f_num not in fnum_to_records:
                skipped_not_in_vocab += 1
                continue

            # Filter records to match numbers in query
            records = filter_records_by_query(text, fnum_to_records[f_num])

            examples.append(
                {
                    "query": text,
                    "f_num": f_num,
                    "source": "labeled",
                    "aff_abbr": aff,
                    "records": records,
                }
            )

    print(f"  {len(examples)} examples loaded")
    print(f"  Skipped: {skipped_no_fnum} no f_num, {skipped_not_in_vocab} not in vocab")

    return examples


def load_synthetic_data(fnum_set, fnum_to_records):
    """Load unaff_synthetic.csv using pre-assigned f_num values."""
    examples = []

    unaff_path = DATA_DIR / "unaff_synthetic.csv"
    if not unaff_path.exists():
        print("  No unaff_synthetic.csv found, skipping")
        return examples

    skipped_no_fnum = 0
    skipped_not_in_vocab = 0

    with open(unaff_path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            text = row["text"]

            fnum_str = row.get("f_num", "").strip()
            if not fnum_str:
                skipped_no_fnum += 1
                continue

            try:
                f_num = int(float(fnum_str))
            except ValueError:
                skipped_no_fnum += 1
                continue

            if f_num not in fnum_set or f_num not in fnum_to_records:
                skipped_not_in_vocab += 1
                continue

            # Filter records to match numbers in query
            records = filter_records_by_query(text, fnum_to_records[f_num])

            examples.append(
                {
                    "query": text,
                    "f_num": f_num,
                    "source": "synthetic",
                    "aff_abbr": "UNAFF",
                    "records": records,
                }
            )

    print(f"  {len(examples)} examples loaded")
    if skipped_no_fnum or skipped_not_in_vocab:
        print(
            f"  Skipped: {skipped_no_fnum} no f_num, {skipped_not_in_vocab} not in vocab"
        )

    return examples


def main():
    # Load vocabularies
    fnum_set = load_vocabularies()

    # Load fnum_to_records
    fnum_to_records = load_fnum_records()

    # Load labeled data
    print("\nLoading labeled data...")
    labeled = load_labeled_data(fnum_set, fnum_to_records)

    # Load synthetic data
    print("\nLoading synthetic data...")
    synthetic = load_synthetic_data(fnum_set, fnum_to_records)

    # Assign splits: labeled data gets train/val/test, synthetic is train only
    print("\nAssigning splits...")
    split_counts = defaultdict(int)

    for ex in labeled:
        ex["split"] = get_split(ex["query"])
        split_counts[ex["split"]] += 1

    for ex in synthetic:
        ex["split"] = "train"
        split_counts["train"] += 1

    # Combine
    examples = labeled + synthetic
    print(f"\nTotal: {len(examples)} examples")
    print(f"  Train: {split_counts['train']} (labeled + synthetic)")
    print(f"  Val: {split_counts['val']} (labeled only)")
    print(f"  Test: {split_counts['test']} (labeled only)")

    # Save
    print(f"\nSaving to {OUTPUT_PATH}...")
    with open(OUTPUT_PATH, "w") as f:
        json.dump(examples, f, indent=2)

    print("Done!")


if __name__ == "__main__":
    main()
